### ISSUE TITLE
glsl file extension detection

### ISSUE THREAD

**Issue by stavenko** [tikhomirov/vim-glsl#13]
Hello.

I'm having a lot of shaders with *.glsl file extension and somehow since last update your plugin does not support them anymore. 

This is usefull to have glsl files, because you might have library files which could be used in *.vert and *.frag files. You combine them concatenated, but you will edit them separately. From the other side this is not good to rename all files in projects. Is it possible to restore *glsl files hightlights?

**Comment by tikhomirov** [comment]
Hi @stavenko,

Thanks for your question

> somehow since last update your plugin does not support them anymore

List of supported file extensions was pretty big so in d25e0a2a I decided to reduce it to the list of file extensions supported by [Khronos reference compiler](https://github.com/KhronosGroup/glslang) to keep it simple.

> this is not good to rename all files in projects

And you don't have to. Just add to your `vimrc`:

```viml
au BufNewFile,BufRead *.glsl set filetype=glsl
```

If you still think that `.glsl` should be supported by this plugin, please fork this repository and prepare PR and we can continue discussion there (though I cannot guarantee that it will be accepted 😄)
